# Generated by Django 3.2.7 on 2021-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(default=0)),
                ('nom', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(default='', max_length=100, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(default=0)),
                ('nom', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(default='', max_length=100, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(default=0)),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('addresse', models.CharField(default='', max_length=200, verbose_name='Prénom')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
    ]
