# Generated by Django 3.2.7 on 2021-10-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actes', '0009_auto_20211025_0912'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_last_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('identifiant', models.IntegerField(default=0)),
                ('numero', models.CharField(default='', max_length=15)),
                ('grade', models.CharField(default='Officier', max_length=8)),
                ('sexe', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_last_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('identifiant', models.IntegerField(default=0)),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('addresse', models.CharField(default='', max_length=200, verbose_name='Adresse')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_last_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('identifiant', models.IntegerField(default=0)),
                ('numero', models.CharField(default='', max_length=15)),
                ('grade', models.CharField(default='Maire', max_length=5)),
                ('sexe', models.CharField(default='', max_length=10)),
                ('mairie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('login_latitude', models.FloatField(default=0)),
                ('login_longitude', models.FloatField(default=0)),
                ('executant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.executant', verbose_name='Executant')),
                ('maire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.maire', verbose_name='Maire')),
                ('mairie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie')),
            ],
        ),
        migrations.AddField(
            model_name='executant',
            name='maire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.maire', verbose_name='Maire'),
        ),
        migrations.AddField(
            model_name='executant',
            name='mairie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie'),
        ),
        migrations.AddField(
            model_name='executant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NaissanceJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('naissance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesnaissancemodel', verbose_name='ActesNaissanceModel')),
            ],
            bases=('Client.loginjournal',),
        ),
        migrations.CreateModel(
            name='MariageJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('mariage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesmariagemodel', verbose_name='ActesMariageModel')),
            ],
            bases=('Client.loginjournal',),
        ),
        migrations.CreateModel(
            name='DecesJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('deces', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesdecesmodel', verbose_name='ActesDecesModel')),
            ],
            bases=('Client.loginjournal',),
        ),
    ]
