# Generated by Django 3.2.7 on 2021-10-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executant',
            name='maire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.maire', verbose_name='Maire'),
        ),
        migrations.AddField(
            model_name='executant',
            name='mairie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie'),
        ),
        migrations.AddField(
            model_name='maire',
            name='mairie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie'),
        ),
        migrations.AlterField(
            model_name='mairie',
            name='addresse',
            field=models.CharField(default='', max_length=200, verbose_name='Adresse'),
        ),
    ]
