# Generated by Django 3.2.7 on 2021-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mairie',
            name='region',
            field=models.CharField(default='MARITIME', max_length=20),
        ),
    ]
