# Generated by Django 3.2.7 on 2021-10-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_auto_20211022_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date_first_creation',
        ),
    ]
