# Generated by Django 3.2.7 on 2021-10-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_remove_journal_date_first_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executant',
            name='date_first_creation',
        ),
        migrations.RemoveField(
            model_name='executant',
            name='date_last_modification',
        ),
        migrations.RemoveField(
            model_name='maire',
            name='date_first_creation',
        ),
        migrations.RemoveField(
            model_name='maire',
            name='date_last_modification',
        ),
        migrations.RemoveField(
            model_name='mairie',
            name='date_first_creation',
        ),
        migrations.RemoveField(
            model_name='mairie',
            name='date_last_modification',
        ),
    ]
