# Generated by Django 3.2.7 on 2021-10-22 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_auto_20211022_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='executant',
            name='date_first_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de parution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executant',
            name='date_last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_first_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de parution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maire',
            name='date_first_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de parution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maire',
            name='date_last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='mairie',
            name='date_first_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de parution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mairie',
            name='date_last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
    ]
