# Generated by Django 3.2.7 on 2021-10-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0008_auto_20211022_1023'),
        ('Client', '0006_auto_20211022_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('login_latitude', models.FloatField(default=0)),
                ('login_longitude', models.FloatField(default=0)),
                ('executant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.executant', verbose_name='Executant')),
                ('maire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.maire', verbose_name='Maire')),
                ('mairie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.mairie', verbose_name='mairie')),
            ],
        ),
        migrations.CreateModel(
            name='DecesJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('deces', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesdecesmodel', verbose_name='ActesDecesModel')),
            ],
            bases=('Client.loginjournal',),
        ),
        migrations.CreateModel(
            name='MariageJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('mariage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesmariagemodel', verbose_name='ActesMariageModel')),
            ],
            bases=('Client.loginjournal',),
        ),
        migrations.CreateModel(
            name='NaissanceJournal',
            fields=[
                ('loginjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Client.loginjournal')),
                ('naissance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Actes.actesnaissancemodel', verbose_name='ActesNaissanceModel')),
            ],
            bases=('Client.loginjournal',),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
