# Generated by Django 3.2.7 on 2021-10-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_auto_20211025_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mairie',
            name='user',
        ),
    ]
