# Generated by Django 3.2.7 on 2021-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_remove_mairie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='executant',
            name='numero',
            field=models.CharField(default='', max_length=15),
        ),
    ]
