# Generated by Django 3.2.7 on 2021-10-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_executant_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='executant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='maire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='maire',
            name='prenom',
        ),
    ]
