# Generated by Django 3.2.7 on 2021-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_auto_20211027_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='mairie',
            name='numero',
            field=models.CharField(default='', max_length=15),
        ),
    ]
