# Generated by Django 3.2.7 on 2021-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_mairie_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mairie',
            name='numero',
        ),
        migrations.AddField(
            model_name='maire',
            name='numero',
            field=models.CharField(default='', max_length=15),
        ),
    ]
