# Generated by Django 3.2.7 on 2021-10-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActesNaissanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le', models.CharField(max_length=300, verbose_name='Le')),
                ('heure', models.IntegerField(verbose_name='heure(s)')),
                ('minutes', models.IntegerField(verbose_name='minute(s)')),
                ('est_ne_ville', models.CharField(max_length=25, verbose_name='est né à (Ville)')),
                ('est_ne_pays', models.CharField(max_length=25, verbose_name='(Pays)')),
                ('nom', models.CharField(max_length=25, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('sexe', models.CharField(max_length=15, verbose_name='sexe')),
                ('parent_1', models.CharField(max_length=50, verbose_name='Fils (e) de (Père)')),
                ('parent_1_naissance_date', models.CharField(max_length=30, verbose_name='Date de naissance du père')),
                ('parent_1_naissance_lieu', models.CharField(max_length=40, verbose_name='Lieu de naissance du père')),
                ('parent_1_profession', models.CharField(max_length=20, verbose_name='Profession du père')),
                ('parent_1_domicile', models.CharField(max_length=50, verbose_name='Domicile du père')),
                ('parent_2', models.CharField(max_length=50, verbose_name='Fils (e) de (Mère)')),
                ('parent_2_naissance_date', models.CharField(max_length=30, verbose_name='Date de naissance de la mère')),
                ('parent_2_naissance_lieu', models.CharField(max_length=40, verbose_name='Lieu de naissance de la mère')),
                ('parent_2_profession', models.CharField(max_length=20, verbose_name='Profession de la mère')),
                ('parent_2_domicile', models.CharField(max_length=30, verbose_name='Domicile de la mère')),
                ('dresse_le', models.CharField(max_length=100, verbose_name='Dressé le')),
                ('dresse_le_heure', models.IntegerField(verbose_name='Dressé le (minutes)')),
                ('dresse_le_minutes', models.IntegerField(verbose_name='Dressé le (minutes)')),
                ('dresse_le_decla', models.CharField(max_length=200, verbose_name='sur la déclaration de')),
                ('dresse_le_age', models.IntegerField(verbose_name='Dressé âges')),
                ('dresse_domicile', models.CharField(max_length=30, verbose_name='Dressé domicile')),
                ('dresse_lecture', models.CharField(max_length=200, verbose_name='avec Nous')),
            ],
        ),
    ]
