# Generated by Django 3.2.7 on 2021-10-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0002_rename_minutes_actesnaissancemodel_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='actesnaissancemodel',
            name='scan_manuscrit',
            field=models.FileField(default='', upload_to='actes_naissance_original/'),
        ),
    ]
