# Generated by Django 3.2.7 on 2021-10-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0003_actesnaissancemodel_scan_manuscrit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActesDecesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le', models.CharField(default='', max_length=300, verbose_name='Le')),
                ('heure', models.IntegerField(default=0, verbose_name='Heure(s)')),
                ('minute', models.IntegerField(default=0, verbose_name='minutes(s)')),
                ('est_mort_ville', models.CharField(default='', max_length=30, verbose_name='est décédé (e) à (ville)')),
                ('est_mort_pays', models.CharField(default='', max_length=30, verbose_name='(Pays)')),
                ('nom', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(default='', max_length=100, verbose_name='Prénom(s)')),
                ('sexe', models.CharField(default='', max_length=15, verbose_name='de sexe')),
                ('date_naissance', models.CharField(default='', max_length=30, verbose_name='est né ')),
                ('lieu_naissance', models.CharField(default='', max_length=30, verbose_name='à')),
                ('profession', models.CharField(default='', max_length=20, verbose_name='Profession')),
                ('domicile', models.CharField(default='', max_length=20, verbose_name='Domiciliée à')),
                ('parent_1', models.CharField(default='', max_length=100, verbose_name='Fils (le) de')),
                ('parent_2', models.CharField(default='', max_length=100, verbose_name='et de')),
                ('parent_1_profession', models.CharField(default='', max_length=20, verbose_name='Profession')),
                ('parent_1_domicile2', models.CharField(default='', max_length=100, verbose_name='Domiciliée à')),
                ('parent_2_profession', models.CharField(default='', max_length=20, verbose_name='Profession')),
                ('parent_2_domicile2', models.CharField(default='', max_length=100, verbose_name='Domiciliée à')),
                ('dresse_le', models.CharField(max_length=100, verbose_name='Dressé le')),
                ('dresse_le_heure', models.IntegerField(verbose_name='Dressé le (minutes)')),
                ('dresse_le_minutes', models.IntegerField(verbose_name='Dressé le (minutes)')),
                ('dresse_le_decla', models.CharField(max_length=200, verbose_name='sur la déclaration de')),
                ('dresse_le_age', models.IntegerField(verbose_name='Dressé âges')),
                ('dresse_domicile', models.CharField(max_length=30, verbose_name='Dressé domicile')),
                ('dresse_lecture', models.CharField(max_length=200, verbose_name='avec Nous')),
                ('scan_manuscrit', models.FileField(default='', upload_to='actes_naissance_original/')),
            ],
        ),
    ]
