# Generated by Django 3.2.7 on 2021-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0004_actesdecesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActesMariageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le', models.CharField(default='', max_length=300, verbose_name='Le')),
                ('heure', models.IntegerField(default=0, verbose_name='heures(s)')),
                ('minute', models.IntegerField(default=0, verbose_name='minutes(s)')),
                ('sep', models.CharField(default='', max_length=2, verbose_name="devant NOUS\nOfficier de l'Etat Civil, ont comparu publiquement dans la commune du Golfe 1  (Lomé-TOGO)")),
                ('nom1', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom1', models.CharField(default='', max_length=100, verbose_name='Prénom(s)')),
                ('nationalite1', models.CharField(default='', max_length=25, verbose_name='de Nationalité')),
                ('ne_le_homme', models.CharField(default='', max_length=30, verbose_name='Date de naissance (Homme)')),
                ('profession1', models.CharField(default='', max_length=20, verbose_name='Profession')),
                ('domicile1', models.CharField(default='', max_length=20, verbose_name='Domicilié à')),
                ('homme_parent_1', models.CharField(default='', max_length=100, verbose_name='Fils majeur/mineur de')),
                ('homme_parent_2', models.CharField(default='', max_length=100, verbose_name='Et de')),
                ('nom2', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom2', models.CharField(default='', max_length=100, verbose_name='Prénom(s)')),
                ('nationalite2', models.CharField(default='', max_length=20, verbose_name='de Nationalité')),
                ('ne_le_femme', models.CharField(default='', max_length=30, verbose_name='Date de naissance (Femme)')),
                ('profession2', models.CharField(default='', max_length=20, verbose_name='Profession')),
                ('domicile2', models.CharField(default='', max_length=20, verbose_name='Domicilié à')),
                ('femme_parent_1', models.CharField(default='', max_length=100, verbose_name='Fils majeur/mineur de')),
                ('femme_parent_2', models.CharField(default='', max_length=100, verbose_name='Et de')),
                ('contrat_mariage', models.CharField(default='', max_length=100, verbose_name='Contrat de mariage')),
                ('option', models.CharField(default='', max_length=50, verbose_name='Option')),
                ('sep2', models.CharField(default='', max_length=2, verbose_name="Les futurs époux décidèrent l'un après l'autre se prendre\n    pour époux et nous avons prononcé au nom de la loi qu'ils sont unis par le mariage en \n    présence de ")),
                ('present_1', models.CharField(default='', max_length=100, verbose_name='1/')),
                ('present_2', models.CharField(default='', max_length=100, verbose_name='2/')),
                ('dresse_lecture', models.CharField(default='', max_length=100, verbose_name='tous deux témoins majeurs qui lecture faite, ont signé avec les époux et NOUS')),
                ('scan_manuscrit', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Executant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(default='', max_length=100, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Maire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(default='', max_length=100, verbose_name='Prénom')),
            ],
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50, verbose_name='Nom')),
                ('addresse', models.CharField(default='', max_length=200, verbose_name='Prénom')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
            ],
        ),
    ]
