# Generated by Django 3.2.7 on 2021-10-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0005_actesmariagemodel_executant_maire_mairie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actesdecesmodel',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actesmariagemodel',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actesnaissancemodel',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executant',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maire',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mairie',
            name='identifiant',
            field=models.IntegerField(default=0),
        ),
    ]
