# Generated by Django 3.2.7 on 2021-10-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0006_auto_20211022_0807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executant',
        ),
        migrations.DeleteModel(
            name='Maire',
        ),
        migrations.DeleteModel(
            name='Mairie',
        ),
    ]
