# Generated by Django 3.2.7 on 2021-10-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actes', '0007_auto_20211022_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actesdecesmodel',
            name='scan_manuscrit',
            field=models.FileField(default='', upload_to='actes_deces_original/'),
        ),
        migrations.AlterField(
            model_name='actesmariagemodel',
            name='scan_manuscrit',
            field=models.FileField(upload_to='actes_mariage_original/'),
        ),
    ]
